#!/usr/bin/env python3

# Created by: Adam Diwani
# Created on: January 4th, 2021
# This program converts celsius to fahrenheit


def fahrenheit():

    while True:
        # Input
        Celsius_string =input("Enter a temperature(In degrees celsius): ")
    
        #Process
        try:
            
            Celsius = int(Celsius_string)
            break
        
        except Exception:
            print("This is not a number, therefore it is not a valid temperature")
            
    Fahrenheit = Celsius * (9/5) + 32
    
        #Output
    print("the temperature in fahrenheit is {} degrees".format(Fahrenheit))
    
    
def main():
    fahrenheit()
        
if __name__ == "__main__":
        main()
